### ISSUE TITLE
Plugin dosent load

### ISSUE THREAD

**Issue by gaberilde** [Justugh/Proxy-Fix#1]
Throught because i was using a fork of Bungeecord but it happens even on pretty much the latest version of bungeecord.

```
13:23:23 [WARNING] Error enabling plugin ProxyFix
java.lang.NoClassDefFoundError: org/bukkit/event/Listener
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader
.java:34)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.
java:27)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:
304)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:2
12)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:268)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.Listener
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader
.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.
java:27)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 18 more
```

**Comment by Justugh** [comment]
It's a spigot plugin, putting it on the Bungeecord would stop nothing, due to them using a different Bungeecord instance to join your server.

**Comment by gaberilde** [comment]
Oh right sorry but you did not make it clear enough since it said it was for bungee and it was in the bungee section and it confused me...

**Comment by Justugh** [comment]
It's okay, sorry to cause the confusion!
